### ISSUE TITLE
Hiting the exporter endpoint with browser to test gets error

### ISSUE THREAD

**Issue by Daxcor69** [MikeDombo/xen-exporter#3] opened 2023-01-06 21:50 UTC
I have installed the exporter in kubernetes as a pod.  I is up and running with no issues.  When I hit the endpoint I get a blank screen and the logs from the exporter pod is:

```
10.96.6.40 - - [06/Jan/2023 21:43:39] "GET / HTTP/1.1" 200 -
----------------------------------------
Exception occurred during processing of request from ('10.96.6.40', 36588)
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/socketserver.py", line 316, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/local/lib/python3.10/socketserver.py", line 347, in process_request
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.10/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/app/xen-exporter.py", line 222, in __init__
    super().__init__(request, client_address, server)
  File "/usr/local/lib/python3.10/socketserver.py", line 747, in __init__
    self.handle()
  File "/usr/local/lib/python3.10/http/server.py", line 433, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.10/http/server.py", line 421, in handle_one_request
    method()
  File "/app/xen-exporter.py", line 228, in do_GET
    self.wfile.write(collect_metrics().encode("utf-8"))
  File "/app/xen-exporter.py", line 140, in collect_metrics
    res = urllib.request.urlopen(
  File "/usr/local/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/usr/local/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/usr/local/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/usr/local/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 500: Internal Error```

Can you help me diagnose this error?

running xcp-ng host 8.2.1

**Comment by Daxcor69** [comment] 2023-01-06 21:52
I did have an auth error, and I fixed the password, then I got this error. So am pretty sure that the exporter is talking to the xcp host correctly as it seems to have passed the auth stage.

**Comment by MikeDombo** [comment] 2023-01-06 21:55
https://github.com/MikeDombo/xen-exporter/blob/master/xen-exporter.py#L140-L142

The http 500 error is coming from the xenserver (or whatever is on 10.96.6.40). You should have a look at xen's logs.

**Comment by MikeDombo** [comment] 2023-01-06 21:59
"10.96.6.40 - - [06/Jan/2023 21:43:39] "GET / HTTP/1.1" 200"

This is the same IP. What settings are you using?

**Comment by Daxcor69** [comment] 2023-01-06 22:02
this is a snippet from the kubernetes manifests.

```
      containers:
        - name: xcp-1-exporter
          env:
            - name: XEN_HOST
              value: "10.1.1.4"
            - name: XEN_USER
              value: "root"
            - name: XEN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: xcp-1-exporter
                  key: secretkey
            - name: XEN_SSL_VERIFY
              value: "false"
          image: ghcr.io/mikedombo/xen-exporter:latest```

10.96.6.40 is the ip of the exporter pod,  xcp is located at 10.1.1.4.  Yes the pod can talk to that IP

**Comment by MikeDombo** [comment] 2023-01-06 22:06
Alright, that seems reasonable.

So have a look at the logs then on the xen host to determine the cause for the http 500.

**Comment by Daxcor69** [comment] 2023-01-06 22:10
when I hit this url

wget  http://root:password@10.1.1.4/host_rrd

with the right creds, it works just fine.

I am still looking for the xcp-ng logs.  I am using the   xcp-ng Center desktop app and don't see any logs. I might have to look on the machine itself.

**Comment by MikeDombo** [comment] 2023-01-06 22:14
You need to ssh into the machine.

Look at:
`less /var/log/xcp-rrdd-plugins.log`
`less /var/log/xensource.log`

and syslogs `dmesg syslog -T`

**Comment by Daxcor69** [comment] 2023-01-06 22:18
less /var/log/xcp-rrdd-plugins.log
`Jan  6 06:47:46 foundry1 xcp-rrdd-gpumon: [error||0 ||xcp-rrdd-gpumon] Unexpected error (Failure "not enough memory"), sleeping for 10 seconds...`

less /var/log/xensource.log
there is a lot there still trying to sort it out.

syslog, nothing current, Nothing since dec 30th

**Comment by Daxcor69** [comment] 2023-01-06 22:22
```
Jan  6 06:52:50 foundry1 xapi: [debug||1450492 HTTP 127.0.0.1->:::80|session.login_with_password D:6602593f2c52|xapi_session] Success: local auth, user root from HTTP request from Internet with User-Agent: xen-api-libs/1.0
Jan  6 06:52:50 foundry1 xapi: [ info||1450492 HTTP 127.0.0.1->:::80|session.login_with_password D:6602593f2c52|xapi_session] Session.create trackid=e67e1746949f498298cef61f33968a1a pool=false uname=root originator=xapi/1.20 is_local_superuser=true auth_user_sid= parent=trackid=9834f5af41c964e225f24279aefe4e49
Jan  6 06:52:50 foundry1 xapi: [debug||1450493 /var/lib/xcp/xapi||dummytaskhelper] task dispatch:pool.get_all D:09953217a8c8 created by task D:6602593f2c52
Jan  6 06:52:50 foundry1 xapi: [debug||1450488 HTTPS 10.1.1.111->:::80|Get RRD updates. D:6f6c66557323|xapi_services] hand_over_connection GET /rrd_updates to /var/lib/xcp/xcp-rrdd.forwarded
Jan  6 06:52:50 foundry1 xapi: [ info||1450494 HTTP 127.0.0.1->:::80|session.logout D:14ce6d5c7d58|xapi_session] Session.destroy trackid=e67e1746949f498298cef61f33968a1a
Jan  6 06:52:50 foundry1 xapi: [ info||1450486 HTTPS 10.1.1.111->:::80|session.logout D:6aca864ea18f|xapi_session] Session.destroy trackid=c06c84ffd5fc6f2d587733b56e797a80
Jan  6 06:52:53 foundry1 xapi: [debug||1450495 /var/lib/xcp/xapi||dummytaskhelper] task dispatch:session.logout D:d465b37924d6 created by task D:fa229619a23c
Jan  6 06:52:53 foundry1 xapi: [ info||1450495 /var/lib/xcp/xapi|session.logout D:209275e79ae0|xapi_session] Session.destroy trackid=8134426be1457290f71b75808fa286ee
Jan  6 06:52:53 foundry1 xapi: [debug||1450496 /var/lib/xcp/xapi||dummytaskhelper] task dispatch:session.slave_login D:68aaca24d25e created by task D:fa229619a23c
Jan  6 06:52:53 foundry1 xapi: [ info||1450496 /var/lib/xcp/xapi|session.slave_login D:12ead9c66c05|xapi_session] Session.create trackid=59847ed5d7958aac9c659840038b46c1 pool
```

**Comment by MikeDombo** [comment] 2023-01-06 22:37
You can edit `vi /etc/xcp-rrdd.conf`. 

```
# The xcp-rrdd config file

inventory = /etc/xensource-inventory

#disable-logging-for = http
loglevel = debug
```

Then restart rrdd. `systemctl restart xcp-rrdd` ought to work. Then the logs will go into the xensource log file.

**Comment by Daxcor69** [comment] 2023-01-06 22:55
```
Jan  6 07:26:37 foundry1 xcp-rrdd: [debug||109 unix_rpc||http] Request { frame = false; method = POST; uri = /var/lib/xcp/xcp-rrdd; query = [  ]; content_length = [ 335 ]; transfer encoding = ; version = 1.1; cookie = [ (value filtered) ]; task = ; subtask_of = ; content-type = ; host = localhost; user_agent = /opt/xensource/libexec/xcp-rrdd-plugins/xcp-rrdd-iostat }
Jan  6 07:26:37 foundry1 xcp-rrdd: [ warn||109 unix_rpc||http] End_of_file (File "http-svr/http_svr.ml", line 418, characters 44-51)
Jan  6 07:26:37 foundry1 xcp-rrdd: [debug||110 unix_rpc||http] Request { frame = false; method = POST; uri = /var/lib/xcp/xcp-rrdd; query = [  ]; content_length = [ 334 ]; transfer encoding = ; version = 1.1; cookie = [ (value filtered) ]; task = ; subtask_of = ; content-type = ; host = localhost; user_agent = /opt/xensource/libexec/xcp-rrdd-plugins/xcp-rrdd-xenpm }
Jan  6 07:26:37 foundry1 xcp-rrdd: [ warn||110 unix_rpc||http] End_of_file (File "http-svr/http_svr.ml", line 418, characters 44-51)
```

**Comment by Daxcor69** [comment] 2023-01-06 22:58
OK, I  need a break, my website is having real issues, and I was hoping to get metrics from the hypervisors so I can look for patterns.   I just don't have time right now to debug this.  Thank you for taking the time to help, I will have to come back to this application.  It looks really promising and useful but I just have to move on to my real issue.

**Comment by MikeDombo** [comment] 2023-01-06 22:59
I don't believe that log is showing your request from this exporter. Make sure you run the exporter and trigger it by hitting its endpoint.

**Comment by MikeDombo** [comment] 2023-02-17 04:16
Closing for now. Reopen as needed with additional information.

**Closed by MikeDombo** 2023-02-17 04:16 UTC
